apiVersion: v1
kind: Pod
metadata:
  name: envconfig
spec:
  containers:
  - image: iam7hills/dockerdemo:envconfig
    name: demo
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
    env:
    - name: ENV_CONFIG
      value: Test
