apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
commonLabels:
  env: deploylabel
images:
- name: iam7hills/dockerdemo
  newTag: tomcatapp-24
configMapGenerator:
- name: configdata
  literals:
  - configname=tomcatvalue
  - databasename=mysqldb-2

