apiVersion: apps/v1
kind: ReplicaSet                                
metadata:
  name: replicasetdemo                          
  labels:
    type: web
spec:
  template:
    metadata:
      name: nginxpods
      labels:
        type: web1
    spec:
      containers:
      - image: iam7hills/learnkubernetes:podsdemo-1.0  # iam7hills/learnkubernetes --> is DockerHub repository and podsdemo-1.0 is the tagname
        name: podsdemo
  replicas: 3
  selector:
    matchLabels:
      type: web1
