apiVersion: v1
kind: Pod
metadata:
  name: secretvol
spec:
  volumes:
  - name: volumemap
    secret:
      secretName: secretdemo 
  containers:
  - image: iam7hills/dockerdemo:configmapdemo
    name: demo
    imagePullPolicy: Always
    volumeMounts:
    - name: volumemap
      mountPath: /tmp

